import type { Metadata } from "next";
import { DM_Sans } from "next/font/google";
import Navbar from "@/ui/Navbar/Navbar";

const DMSans = DM_Sans();

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${DMSans.className} antialiased`}>
        <div className="mb-16">
          <Navbar />
        </div>
        {children}
      </body>
    </html>
  );
}
